In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

Norm = (Xn - Mean) / sqrt(var) + Bias

output= γ x Norn + β

In [20]:
emb_dim = 5
x = torch.randn(emb_dim,emb_dim)
print("Input: \n",x)
mean = x.mean(dim=-1, keepdim=True)
print("mean: \n", mean)
var = x.var(dim=-1, keepdim=True, unbiased=False)
print("Var: \n",var)
norm_x = (x - mean) / torch.sqrt(var)
print("Normalized: \n", norm_x)
scale = nn.Parameter(torch.ones(emb_dim))
shift = nn.Parameter(torch.zeros(emb_dim))
print("output: \n",scale * norm_x + shift)

Input: 
 tensor([[ 1.0432, -0.4373, -0.4381, -0.9943, -0.4806],
        [ 0.5127, -0.6062,  2.7588,  0.2721,  0.3402],
        [-0.8790, -0.6727, -0.9688,  0.3121, -0.6983],
        [-1.0394, -0.0273,  2.1519, -1.3810, -0.3632],
        [-0.4677, -1.0672,  0.5600,  0.1748, -0.4831]])
mean: 
 tensor([[-0.2614],
        [ 0.6555],
        [-0.5813],
        [-0.1318],
        [-0.2567]])
Var: 
 tensor([[0.4699],
        [1.2565],
        [0.2118],
        [1.5328],
        [0.3212]])
Normalized: 
 tensor([[ 1.9033, -0.2566, -0.2577, -1.0691, -0.3198],
        [-0.1274, -1.1256,  1.8764, -0.3421, -0.2813],
        [-0.6467, -0.1985, -0.8419,  1.9414, -0.2542],
        [-0.7331,  0.0844,  1.8446, -1.0090, -0.1869],
        [-0.3724, -1.4303,  1.4409,  0.7614, -0.3996]])
output: 
 tensor([[ 1.9033, -0.2566, -0.2577, -1.0691, -0.3198],
        [-0.1274, -1.1256,  1.8764, -0.3421, -0.2813],
        [-0.6467, -0.1985, -0.8419,  1.9414, -0.2542],
        [-0.7331,  0.0844,  1.8446, -1.0090, -0.

In [3]:
class LayerNorm(nn.Module):
    def __init__(self, emb_dim, eps = 1e-5):
        super().__init__()
        self.eps = eps
        
    def forward(self, x):
        mean = x.mean(dim=-1, keepdim=True)
        var = x.var(dim=-1, keepdim=True, unbiased=False)
        norm_x = (x - mean) / torch.sqrt(var + self.eps)
        return norm_x 
    
x = torch.randn(2,10,64)
layer_noem = LayerNorm(64)
out = layer_noem(x)
print("LayerNormilization:", out.shape)

LayerNormilization: torch.Size([2, 10, 64])


2) RMS Normalization \
RMS = sqrt(Xn ** 2) \
Norm = Xn / RMS

In [17]:
emb_dim = 5
x = torch.randn(emb_dim,emb_dim)
print("input:\n",x)
norm = x.pow(2).mean(-1,keepdim=True)
print("norm\n",norm)
rms = norm.sqrt()
print(x / rms)

input:
 tensor([[ 0.0143,  1.3155, -1.0412, -1.0749, -0.4050],
        [-1.8107, -0.0966, -0.5734,  0.3878,  0.0586],
        [-2.1826,  1.6112,  0.3361, -0.8314, -0.5167],
        [-1.9822, -0.0976,  0.4469, -0.2784, -0.8674],
        [-1.6510,  0.5052,  0.5152, -0.7589, -1.9927]])
norm
 tensor([[0.8269],
        [0.7541],
        [1.6862],
        [0.9936],
        [1.5586]])
tensor([[ 0.0157,  1.4467, -1.1450, -1.1821, -0.4454],
        [-2.0851, -0.1112, -0.6603,  0.4465,  0.0675],
        [-1.6808,  1.2408,  0.2588, -0.6403, -0.3979],
        [-1.9885, -0.0979,  0.4483, -0.2793, -0.8702],
        [-1.3224,  0.4046,  0.4127, -0.6078, -1.5961]])


In [ ]:
class RMSNormilization(nn.Module):
    
    def __init__(self,dim,eps=1e-8):
        super().__init__()
        self.eps = eps
        self.weight = nn.Parameter(torch.ones(dim))
        
    def forward(self,x):
        rms = x.pow(2).mean(-1,keepdim=True).sqrt()
        return self.weight * x / (rms + self.eps)
    
x = torch.randn(2,10,64)
rms = RMSNormilization(64)
out = rms(x)
print("RMSNormilization:", out.shape)