In [1]:
import torch
import torch.nn as nn
import tiktoken

In [2]:
data = """Alfonso was the son of King Peter III of Aragon and Constance, daughter and heiress of King Manfred of Sicily.
Soon after assuming the throne, he conducted a campaign to reincorporate the Balearic Islands into the Kingdom of Aragon,
which had been lost due to the division of the kingdom by his grandfather, James I of Aragon. Thus in 1285 he declared war on his uncle,
James II of Majorca, and conquered both Majorca (1285) and Ibiza (1286), effectively reassuming suzerainty over the Kingdom of Majorca. 
He followed this with the conquest of Menorca – until then an autonomous Muslim state (Manûrqa) within the Kingdom of Majorca – on 17 January 1287,
the anniversary of which now serves as Menorca's national holiday. Alfons"""

In [15]:
data[:10]

'Alfonso wa'

In [31]:
# letter tokenizer
def letter_tokenizer(data):
    vocab = sorted(set(data))  # sorted list of unique characters
    letter2idx = {letter: idx for idx, letter in enumerate(vocab)}  # mapping
    return [letter2idx[letter] for letter in data]

In [ ]:
# Bite pair (BPE) Embedding using tokienizer
def Embedding_using_tiktoken(data,vocab_size,embedding_dim,model: str):
    # 'gpt2', 'r50k_base', 'p50k_base', 'p50k_edit', 'cl100k_base', 'o200k_base'
    Embedding = tiktoken.get_encoding(model)
    tokens = Embedding.encode(data)
    embedding_layer = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)
    tensors = torch.tensor(tokens)
    embedded = embedding_layer(tensors)
    return embedded

In [39]:
Embedding_using_tiktoken("a",vocab_size=100,embedding_dim=20,model="gpt2")

torch.Size([1, 20])


tensor([[ 1.5226,  0.3926,  2.2044, -0.9322,  1.0402,  0.9161,  0.3169,  1.6389,
          0.5041, -0.1986, -0.2390, -1.5644,  1.9477,  0.1566, -0.2564,  0.2717,
         -0.8470, -0.7566,  0.6189,  0.3601]], grad_fn=<EmbeddingBackward0>)

In [4]:
# word level tokenizer
def word_tokenizer(data):
    vocab = list(set(data.split()))
    vocab.sort()
    vocab = {word:i for i, word in enumerate(vocab)}
    return vocab

In [9]:
def Embedding_using_tiktoken(data,embedding_dim,model: str):
    # 'gpt2', 'r50k_base', 'p50k_base', 'p50k_edit', 'cl100k_base', 'o200k_base'
    tokenizer = tiktoken.get_encoding(model)
    vocab_size = tokenizer.n_vocab
    print("vocab_size",vocab_size)
    tokens = tokenizer.encode(data)
    print(tokens)
    embedding_layer = nn.Embedding(num_embeddings = vocab_size, embedding_dim = embedding_dim)
    tensors = torch.tensor(tokens)
    embedded = embedding_layer(tensors)
    return embedded

In [10]:
vocab = Embedding_using_tiktoken("data",embedding_dim=20,model="gpt2")
print(vocab)

vocab_size 50257
[7890]
tensor([[-2.1035, -0.8275, -1.3066,  1.1421, -0.3811,  0.1235, -0.3347, -0.7177,
          1.5479,  0.0102, -0.8004, -0.9478,  1.0887,  0.9400, -0.1822,  1.2883,
          0.6631, -0.6143,  0.3860, -0.8972]], grad_fn=<EmbeddingBackward0>)


In [2]:
tokenizer = tiktoken.get_encoding("gpt2")

In [3]:
tokenizer.n_vocab

50257

In [8]:
a=[]
letters = 'abcdefghijklmnopqrstuvwxyz'
a.extend(list(letters))

In [9]:
len(a)

26

In [10]:
word = "."
indices = bpe_tokenizer(word)
indices

[13]

In [11]:
# Initialize Embedding Layer (PyTorch)
vocab_size = size
embedding_dim = 64  # You can choose 64, 128, 512, etc.

embedding_layer = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)

In [12]:
# Convert Indices to Embeddings
input_indices = torch.tensor(indices)  # [2, 3, 5, 6]
embedded = embedding_layer(input_indices)

print(embedded.shape)  # torch.Size([seq_len, embedding_dim])

torch.Size([1, 64])


In [84]:
embedded

tensor([[-0.1885,  0.6524,  1.8010, -0.1441,  0.6679, -0.7413,  0.9841,  0.1648,
          0.1954,  0.1985,  0.2728, -0.5197, -0.0283, -1.3518,  0.0278, -0.7219,
          0.3211, -1.4515,  1.5537,  1.6713,  0.7000, -1.6238, -1.7118,  1.1070,
         -1.0822,  0.0844, -0.8723, -1.3363, -0.5253,  1.8952, -0.4397,  1.7579,
         -0.1163,  0.3455,  1.1743,  0.0954, -0.3606,  0.4404, -0.5364,  0.0727,
         -0.0048,  2.6669, -0.7193,  0.0812,  0.5284, -0.1612,  1.2484,  0.2918,
          2.1587, -0.7336, -0.5229, -0.7572,  0.8994, -0.0975, -0.6601,  1.9823,
         -0.9406,  0.5878, -0.6954,  0.9455,  0.1982, -0.5327, -1.6737, -1.6194]],
       grad_fn=<EmbeddingBackward0>)